In [56]:
import pandas as pd
import numpy as np

In [60]:
imdb = pd.read_excel("imdb.xlsx")
imdb

,fn,tid,title,wordsInTitle,url,imdbRating,ratingCount,duration,year,type,...,Short,Sport,TalkShow,Thriller,War,Western,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,titles01/tt0012349,tt0012349,Der Vagabund und das Kind (1921),der vagabund und das kind,http://www.imdb.com/title/tt0012349/,8.4,40550,3240,1921,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,titles01/tt0015864,tt0015864,Goldrausch (1925),goldrausch,http://www.imdb.com/title/tt0015864/,8.3,45319,5700,1925,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
2,titles01/tt0017136,tt0017136,Metropolis (1927),metropolis,http://www.imdb.com/title/tt0017136/,8.4,81007,9180,1927,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
3,titles01/tt0017925,tt0017925,Der General (1926),der general,http://www.imdb.com/title/tt0017925/,8.3,37521,6420,1926,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4,titles01/tt0021749,tt0021749,Lichter der GroÃŸstadt (1931),lichter der gro stadt,http://www.imdb.com/title/tt0021749/,8.7,70057,5220,1931,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14756,titles04/index.html.9989,tt0672488,Peep Show Sectioning (TV Episode 2005),peep show sectioning tv episode,http://www.imdb.com/title/tt0672488/,7.7,135,1440,2005,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14757,titles04/index.html.9992,tt0675644,Playhouse 90 The Miracle Worker (TV Episode 1957),playhouse the miracle worker tv episode,http://www.imdb.com/title/tt0675644/,7.3,8,5400,1957,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14758,titles04/index.html.9994,tt0679222,Private Screenings Robert Mitchum and Jane Rus...,private screenings robert mitchum and jane rus...,http://www.imdb.com/title/tt0679222/,7,20,3600,1996,video.episode,...,0,0,1,0,0,0,NaN,NaN,NaN,NaN
14759,titles04/index.html.9995,tt0680064,Providence All the King's Men (TV Episode 2002),providence all the king s men tv episode,http://www.imdb.com/title/tt0680064/,NaN,NaN,3600,2002,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14760,titles04/index.html.9997,tt0681024,QI Adam (TV Episode 2003),qi adam tv episode,http://www.imdb.com/title/tt0681024/,7.6,89,1800,2003,video.episode,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

7. Get the imdb rating for fifth movie of dataframe

In [20]:
rating = imdb.loc[4, 'imdbRating']
rating

8.7

8. Return titles of movies with shortest and longest run time

In [64]:
shortest_movie = imdb.loc['duration'].min(), 'title'
longest_movie = imdb.loc['duration'].max(), 'title'

shortest_movie
longest_movie


# imdb['duration'].min()

9. Sort the data frame by in the order of when they were released and have higher ratings, Hint : release_date (earliest) and Imdb rating(highest to lowest)

In [23]:
imdb.head()

,fn,tid,title,wordsInTitle,url,imdbRating,ratingCount,duration,year,type,...,Short,Sport,TalkShow,Thriller,War,Western,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,titles01/tt0012349,tt0012349,Der Vagabund und das Kind (1921),der vagabund und das kind,http://www.imdb.com/title/tt0012349/,8.4,40550,3240,1921,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,titles01/tt0015864,tt0015864,Goldrausch (1925),goldrausch,http://www.imdb.com/title/tt0015864/,8.3,45319,5700,1925,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
2,titles01/tt0017136,tt0017136,Metropolis (1927),metropolis,http://www.imdb.com/title/tt0017136/,8.4,81007,9180,1927,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
3,titles01/tt0017925,tt0017925,Der General (1926),der general,http://www.imdb.com/title/tt0017925/,8.3,37521,6420,1926,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4,titles01/tt0021749,tt0021749,Lichter der GroÃŸstadt (1931),lichter der gro stadt,http://www.imdb.com/title/tt0021749/,8.7,70057,5220,1931,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

In [22]:
imdb.sort_values(['year', 'imdbRating'], ascending=[True, False])

,fn,tid,title,wordsInTitle,url,imdbRating,ratingCount,duration,year,type,...,Short,Sport,TalkShow,Thriller,War,Western,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
12908,titles04/index.html.6808,tt0214388,Eins\,zwei\,Pie - Wer die Qual hat\,hat die Wahl (2000),eins zwei pie wer die qual hat hat die wahl,http://www.imdb.com/title/tt0214388/,5.9,16813,...,0,1,0,0,0,0,0.0,0.0,0.0,NaN
6469,titles03/index.html.6671,tt2575400,CinÃ©mas d'Horreur - Apocalypse\,Virus\,Zombies (2010),cin mas d horreur apocalypse virus zombies,http://www.imdb.com/title/tt2575400/,7.2,6,3300,...,0,0,0,0,0,0,0.0,0.0,NaN,NaN
7008,titles04/index.html.10175,tt0763034,Die Simpsons Marge vs. Singles\,Seniors\,Childless Couples and Teens\,and Gays (TV Episode 2004),die simpsons marge vs singles seniors childles...,http://www.imdb.com/title/tt0763034/,6.6,394,...,0,0,0,0,0,0,0.0,0.0,0.0,NaN
728,titles02/index.html.2403,tt1340800,Dame\,KÃ¶nig\,As\,Spion (2011),dame k nig as spion,http://www.imdb.com/title/tt1340800/,7.1,115003,...,0,0,0,0,0,0,1.0,0.0,0.0,NaN
1336,titles02/index.html.4621,tt0243714,Bube\,Dame\,KÃ¶nig\,grAs - Die Serie (TV Series 2000â€“ ),bube dame k nig gras die serie tv series,http://www.imdb.com/title/tt0243714/,7.6,687,...,0,0,0,0,0,0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8432,titles04/index.html.12578,tt1602615,Summer Hours,summer hours,http://www.imdb.com/title/tt1602615/,NaN,NaN,NaN,NaN,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
8870,titles04/index.html.13318,tt1922570,Icarus Factor,icarus factor,http://www.imdb.com/title/tt1922570/,NaN,NaN,NaN,NaN,video.movie,...,0,0,0,1,0,0,NaN,NaN,NaN,NaN
8907,titles04/index.html.13388,tt1965235,Thomas the Tank Engine,thomas the tank engine,http://www.imdb.com/title/tt1965235/,NaN,NaN,NaN,NaN,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14485,titles04/index.html.9493,tt0472429,Voltron,voltron,http://www.imdb.com/title/tt0472429/,NaN,NaN,NaN,NaN,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
14558,titles04/index.html.9608,tt0482548,The Monkey Wrench Gang,the monkey wrench gang,http://www.imdb.com/title/tt0482548/,NaN,NaN,NaN,NaN,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

10. Subset the dataframe with movies having the following parameters. duration between 30 minutes to 180 minutes.

In [35]:
imdb.head()

,fn,tid,title,wordsInTitle,url,imdbRating,ratingCount,duration,year,type,...,Short,Sport,TalkShow,Thriller,War,Western,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,titles01/tt0012349,tt0012349,Der Vagabund und das Kind (1921),der vagabund und das kind,http://www.imdb.com/title/tt0012349/,8.4,40550,3240,1921,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,titles01/tt0015864,tt0015864,Goldrausch (1925),goldrausch,http://www.imdb.com/title/tt0015864/,8.3,45319,5700,1925,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
2,titles01/tt0017136,tt0017136,Metropolis (1927),metropolis,http://www.imdb.com/title/tt0017136/,8.4,81007,9180,1927,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
3,titles01/tt0017925,tt0017925,Der General (1926),der general,http://www.imdb.com/title/tt0017925/,8.3,37521,6420,1926,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4,titles01/tt0021749,tt0021749,Lichter der GroÃŸstadt (1931),lichter der gro stadt,http://www.imdb.com/title/tt0021749/,8.7,70057,5220,1931,video.movie,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

In [68]:
# movies_30to180 = imdb[('duration' >= 30) & ('duration' <= 180)]
# movies_30to180.astype(dtype = 'int', errors = 'ignore')

subset_movies = imdb[imdb['duration'].apply(lambda x: 30 <= x <= 180)]
subset_movies